name: Build and Scan

on:
  push:
  pull_request:
    
jobs:
  build-and-scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the app
        run: Docker-compose build
      - name: Run the app
        run: Docker-compose up --detach
      - name: run hawkscan
        uses: stackhawk/hawkscan-action@v1.3.0
        env:
            API_TOKEN: ${{secrets.API_TOKEN}}
        with:
            apiKey: ${{secrets.HAWK_API_KEY}}
            environmentVariable: API_TOKEN